-- returns the color for the given type
return {
    NORMAL = "GRAYMON",
    FIGHTING = "BROWNMON",
    FLYING = "GRAYMON",
    POISON = "PURPLEMON",
    GROUND = "BROWNMON",
    ROCK = "BROWNMON",
    BUG = "GREENMON",
    GHOST = "PURPLEMON",
    FIRE = "REDMON",
    WATER = "BLUEMON",
    GRASS = "GREENMON",
    ELECTRIC = "YELLOWMON",
    PSYCHIC_TYPE = "PURPLEMON",
    ICE = "CYANMON",
    DRAGON = "CYANMON",
    DARK = "PURPLEMON",
    FAIRY = "PINKMON",
    STEEL = "GRAYMON",
}
